package com.example.freizeit.data.repository

import android.content.Context
import android.net.Uri
import androidx.room.withTransaction
import com.example.freizeit.data.BackupData
import com.example.freizeit.data.BackupJsonCodec
import com.example.freizeit.data.BackupParseException
import com.example.freizeit.data.FreizeitDatabase
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Exports/imports the only irreplaceable data — verdicts (favorites among
 * them) and custom POI names. POIs are excluded; they're regenerated by the
 * extraction pipeline import (see [PoiRepository]).
 */
class BackupRepository(
    private val context: Context,
    private val db: FreizeitDatabase
) {

    /** @return number of verdicts + custom names written */
    suspend fun exportTo(uri: Uri): Int = withContext(Dispatchers.IO) {
        val verdicts = db.verdictDao().getAll()
        val customNames = db.poiCustomNameDao().getAll()
        val output = context.contentResolver.openOutputStream(uri)
            ?: throw BackupParseException("Could not open the destination file")
        output.use { stream ->
            OutputStreamWriter(stream, Charsets.UTF_8).use { writer ->
                BackupJsonCodec.write(
                    writer,
                    BackupData(
                        exportedAt = System.currentTimeMillis(),
                        verdicts = verdicts,
                        customNames = customNames
                    )
                )
            }
        }
        verdicts.size + customNames.size
    }

    /**
     * Parses the file at [uri] entirely before writing, then replaces the
     * verdict and custom-name tables in one transaction — a restore is a
     * wholesale replace, not a merge, matching the fresh-install use case.
     *
     * @return number of verdicts + custom names restored
     * @throws BackupParseException on unreadable or malformed files
     */
    suspend fun importFrom(uri: Uri): Int = withContext(Dispatchers.IO) {
        val input = context.contentResolver.openInputStream(uri)
            ?: throw BackupParseException("Could not open the selected file")
        val data = input.use { stream ->
            BackupJsonCodec.read(InputStreamReader(stream, Charsets.UTF_8))
        }
        db.withTransaction {
            db.verdictDao().deleteAll()
            db.verdictDao().upsertAll(data.verdicts)
            db.poiCustomNameDao().deleteAll()
            db.poiCustomNameDao().upsertAll(data.customNames)
        }
        data.verdicts.size + data.customNames.size
    }
}
