package com.example.freizeit.data.repository

import android.content.Context
import android.net.Uri
import androidx.room.withTransaction
import com.example.freizeit.data.BackupData
import com.example.freizeit.data.BackupJsonCodec
import com.example.freizeit.data.BackupParseException
import com.example.freizeit.data.FreizeitDatabase
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Exports/imports the irreplaceable data: verdicts (favorites among them), custom POI names, and
 * custom places (issue #45). OSM `poi` rows are excluded; they're regenerated by the extraction
 * pipeline import (see [PoiRepository]) — `custom_poi` has no such other source of truth, so
 * unlike `poi` it IS included here.
 */
class BackupRepository(
    private val context: Context,
    private val db: FreizeitDatabase
) {

    /** @return number of verdicts + custom names + custom POIs written */
    suspend fun exportTo(uri: Uri): Int = withContext(Dispatchers.IO) {
        val verdicts = db.verdictDao().getAll()
        val customNames = db.poiCustomNameDao().getAll()
        val customPois = db.customPoiDao().getAll()
        val output = context.contentResolver.openOutputStream(uri)
            ?: throw BackupParseException("Could not open the destination file")
        output.use { stream ->
            OutputStreamWriter(stream, Charsets.UTF_8).use { writer ->
                BackupJsonCodec.write(
                    writer,
                    BackupData(
                        exportedAt = System.currentTimeMillis(),
                        verdicts = verdicts,
                        customNames = customNames,
                        customPois = customPois
                    )
                )
            }
        }
        verdicts.size + customNames.size + customPois.size
    }

    /**
     * Parses the file at [uri] entirely before writing, then replaces the verdict, custom-name,
     * and custom-POI tables in one transaction — a restore is a wholesale replace, not a merge,
     * matching the fresh-install use case.
     *
     * @return number of verdicts + custom names + custom POIs restored
     * @throws BackupParseException on unreadable or malformed files
     */
    suspend fun importFrom(uri: Uri): Int = withContext(Dispatchers.IO) {
        val input = context.contentResolver.openInputStream(uri)
            ?: throw BackupParseException("Could not open the selected file")
        val data = input.use { stream ->
            BackupJsonCodec.read(InputStreamReader(stream, Charsets.UTF_8))
        }
        db.withTransaction {
            db.verdictDao().deleteAll()
            db.verdictDao().upsertAll(data.verdicts)
            db.poiCustomNameDao().deleteAll()
            db.poiCustomNameDao().upsertAll(data.customNames)
            db.customPoiDao().deleteAll()
            db.customPoiDao().upsertAll(data.customPois)
        }
        data.verdicts.size + data.customNames.size + data.customPois.size
    }
}
