package com.example.freizeit.data

import com.example.freizeit.data.entity.Favorite
import com.example.freizeit.data.entity.Verdict
import com.google.gson.GsonBuilder
import com.google.gson.JsonArray
import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParseException
import com.google.gson.JsonParser
import java.io.Reader
import java.io.Writer

class BackupParseException(message: String, cause: Throwable? = null) : Exception(message, cause)

data class BackupData(
    val exportedAt: Long,
    val verdicts: List<Verdict>,
    val favorites: List<Favorite>
)

/**
 * The app's own backup format for the only irreplaceable data: verdicts and
 * favorite locations (POIs are excluded — they're regenerated by the
 * extraction pipeline import). Parsed defensively like [PoiJsonParser] since
 * the file can be hand-edited between export and re-import.
 */
object BackupJsonCodec {

    private val gson = GsonBuilder().setPrettyPrinting().create()

    fun write(writer: Writer, data: BackupData) {
        val root = JsonObject()
        root.addProperty("exportedAt", data.exportedAt)
        root.add(
            "verdicts",
            JsonArray().apply {
                data.verdicts.forEach { v ->
                    add(
                        JsonObject().apply {
                            addProperty("placeId", v.placeId)
                            addProperty("value", v.value)
                            addProperty("verdictedAt", v.verdictedAt)
                            addProperty("snapshotName", v.snapshotName)
                            addProperty("snapshotLat", v.snapshotLat)
                            addProperty("snapshotLon", v.snapshotLon)
                            addProperty("snapshotCategory", v.snapshotCategory)
                        }
                    )
                }
            }
        )
        root.add(
            "favorites",
            JsonArray().apply {
                data.favorites.forEach { f ->
                    add(
                        JsonObject().apply {
                            addProperty("name", f.name)
                            addProperty("address", f.address)
                            addProperty("lat", f.lat)
                            addProperty("lon", f.lon)
                        }
                    )
                }
            }
        )
        gson.toJson(root, writer)
    }

    fun read(reader: Reader): BackupData {
        val root = try {
            JsonParser.parseReader(reader)
        } catch (e: JsonParseException) {
            throw BackupParseException("File is not valid JSON", e)
        }
        if (!root.isJsonObject) {
            throw BackupParseException("File is not a Freizeit backup (expected a JSON object)")
        }
        val obj = root.asJsonObject

        val exportedAt = obj.get("exportedAt")
            ?.takeIf { it.isJsonPrimitive && it.asJsonPrimitive.isNumber }
            ?.asLong
            ?: throw BackupParseException("Missing \"exportedAt\"")

        return BackupData(
            exportedAt = exportedAt,
            verdicts = obj.array("verdicts").mapIndexed { i, el -> parseVerdict(el, i) },
            favorites = obj.array("favorites").mapIndexed { i, el -> parseFavorite(el, i) }
        )
    }

    private fun JsonObject.array(key: String): List<JsonElement> {
        val element = get(key) ?: return emptyList()
        if (!element.isJsonArray) throw BackupParseException("\"$key\" is not a list")
        return element.asJsonArray.toList()
    }

    private fun parseVerdict(element: JsonElement, index: Int): Verdict {
        if (!element.isJsonObject) throw BackupParseException("verdicts[$index] is not an object")
        val o = element.asJsonObject
        return Verdict(
            placeId = o.requiredString("placeId", "verdicts", index),
            value = o.requiredString("value", "verdicts", index),
            verdictedAt = o.requiredLong("verdictedAt", "verdicts", index),
            snapshotName = o.optString("snapshotName"),
            snapshotLat = o.requiredDouble("snapshotLat", "verdicts", index),
            snapshotLon = o.requiredDouble("snapshotLon", "verdicts", index),
            snapshotCategory = o.requiredString("snapshotCategory", "verdicts", index)
        )
    }

    private fun parseFavorite(element: JsonElement, index: Int): Favorite {
        if (!element.isJsonObject) throw BackupParseException("favorites[$index] is not an object")
        val o = element.asJsonObject
        return Favorite(
            name = o.requiredString("name", "favorites", index),
            address = o.optString("address"),
            lat = o.requiredDouble("lat", "favorites", index),
            lon = o.requiredDouble("lon", "favorites", index)
        )
    }

    private fun JsonObject.requiredString(key: String, list: String, index: Int): String {
        val value = get(key)
        if (value == null || !value.isJsonPrimitive || !value.asJsonPrimitive.isString) {
            throw BackupParseException("$list[$index] has no \"$key\"")
        }
        return value.asString
    }

    private fun JsonObject.requiredLong(key: String, list: String, index: Int): Long {
        val value = get(key)
        if (value == null || !value.isJsonPrimitive || !value.asJsonPrimitive.isNumber) {
            throw BackupParseException("$list[$index] has no numeric \"$key\"")
        }
        return value.asLong
    }

    private fun JsonObject.requiredDouble(key: String, list: String, index: Int): Double {
        val value = get(key)
        if (value == null || !value.isJsonPrimitive || !value.asJsonPrimitive.isNumber) {
            throw BackupParseException("$list[$index] has no numeric \"$key\"")
        }
        return value.asDouble
    }

    private fun JsonObject.optString(key: String): String? {
        val value = get(key) ?: return null
        if (!value.isJsonPrimitive || !value.asJsonPrimitive.isString) return null
        return value.asString.takeIf { it.isNotBlank() }
    }
}
